name: Build and push docker image

env:
  DOCKER_REGISTRY: ghcr.io

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u $ --password-stdin $DOCKER_REGISTRY
      - run: |
          IMAGE_NAME=$DOCKER_REGISTRY/${{ github.repository }}
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]') # to lowercase
          docker build . -t $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
